service: knockknock

plugins:
  - serverless-api-stage

custom:
  stage: "${opt:stage, self:provider.stage}"
  stageSettings:
    Variables:
      readifyToken: 620b7f44-1303-4faa-a236-bfdf99c9deef
    MethodSettings:
      LoggingLevel: INFO

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  iamRoleStatements:
    -
      Effect: Allow
      Action:
        - logs:*
      Resource: "arn:aws:logs:::*"

functions:
  fibonacci:
    handler: app/handler.fibonacciGet
    events:
      - http:
          path: api/fibonacci
          method: get
          cors: true
  reverseWords:
    handler: app/handler.reverseWordsGet
    events:
      - http:
          path: api/reversewords
          method: get
          cors: true
  token:
    handler: app/handler.tokenGet
    events:
      - http:
          path: api/token
          method: get
          cors: true
  triangleType:
    handler: app/handler.triangleTypeGet
    events:
      - http:
          path: api/triangletype
          method: get
          cors: true
